name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MYSQLDATABASE: sistema_chamados_test
      MYSQLUSER: teste
      MYSQLPASSWORD: teste
      MYSQLHOST: localhost
      MYSQLPORT: 3307
      JWT_SECRET: Estev@nfcteste
      JWT_EXPIRES_IN: 1h

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3307:3306
        env:
          MYSQL_DATABASE: sistema_chamados_test
          MYSQL_USER: teste
          MYSQL_PASSWORD: teste
          MYSQL_ROOT_PASSWORD: root
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Testar conexão com Sequelize
        run: |
          node --input-type=module -e "import sequelize from './src/config/database.js'; await sequelize.authenticate(); console.log('Sequelize conectado ao MySQL'); await sequelize.close();"

      - name: Executar migrations
        run: npx sequelize-cli db:migrate

      - name: Verificar tabelas do banco
        run: |
          mysql -h 127.0.0.1 -P 3307 -u teste -pteste sistema_chamados_test -e "SHOW TABLES;"

      - name: Testar consulta de usuário
        run: |
          node --input-type=module -e "import models from './src/database/models/index.js'; try { const usuario = await models.Usuario.findOne({ where: { email: 'teste@integracao.com' } }); console.log('Usuário encontrado:', usuario); } catch (erro) { console.error('ERRO REAL:', erro); process.exit(1); }"

      - name: Testar criação de usuário
        run: |
          node --input-type=module -e "import models from './src/database/models/index.js'; import bcrypt from 'bcrypt'; import STATUS_CADASTRO from './src/constants/statusCadastro.js'; try { const senha = await bcrypt.hash('123456', 10); const usuario = await models.Usuario.create({ nome: 'Usuário Teste', email: 'teste@integracao.com', senha, cargo: 'USUARIO', statusCadastro: STATUS_CADASTRO.APROVADO }); console.log('Usuário criado:', usuario.toJSON()); } catch (erro) { console.error('ERRO REAL AO CRIAR:', erro); process.exit(1); }"

      - name: Executar testes
        run: npm test -- --runInBand